version: "3.9"
   
services:
    db:
        image: postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=workout
            - POSTGRES_PASSWORD=abc123
        networks:
            - net
    neo4j:
        image: neo4j:4.2.7-community
        network_mode: "bridge"
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_import_file_use__neo4j__config=true
            - NEO4JLABS_PLUGINS=["apoc"]
        volumes:
            - ./neo4j/plugins:/plugins
            - ./neo4j/data:/data
            - ./neo4j/import:/import
        networks:
            - net
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
            - neo4j
        links:
            - neo4j
            - db
        networks:
            - net

networks:
    net:    