# Generated by Django 3.2.4 on 2021-06-17 23:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 23, 26, 29, 833755, tzinfo=utc)),
        ),
    ]
