# Generated by Django 3.2.4 on 2021-06-22 12:00

from django.db import migrations, models
import recommendations.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.DateField(blank=True, default=recommendations.utils.date_now),
        ),
    ]
